### PR TITLE
Update to bundler 2.x and redis_cache_store

### PR DESCRIPTION
**Pull request by jbirdjavi**
I cherry picked some updates that I usually do with Rails 6:  https://jira.cru.org/browse/AP-11

I can attempt to switch to webpacker in another PR if so desired.

### CODE REVIEW

**Comment by soberstadt** [comment]
This is good to merge to staging, we can test there to confirm that it works :)

**Comment by soberstadt** [comment]
@jbirdjavi this is causing https://rollbar.com/Cru/CampusCRM-API/items/18/ when I go to the sidekiq front-end https://campus-contacts-api-stage.cru.org/sidekiq

**Comment by soberstadt** [comment]
But I confirmed that the cache is still working. If we can get sidekiq ui working again we can merge this.
image

**Comment by jbirdjavi** [comment]
@soberstadt A simple gem bump fixed sidekiq web.

**Pull request merged**
